### ISSUE TITLE
Change for 16:9 preview

### ISSUE THREAD

**Issue by MegaV0lt** [glenvt18/vdradmin-am#2]
https://github.com/glenvt18/vdradmin-am/blob/4b819db1d9e3c56750e3aa4db46143a1352179d9/vdradmind.pl#L7109

Please change the values to get a 16:9 preview in the browser.
Personally i changed to 960 / 540 (Half of FullHD) to get is fit in the browser window.

**Comment by glenvt18** [comment]
Here you are e51b695

**Comment by MegaV0lt** [comment]
Great. Thank you!

**Comment by jochenpa** [comment]
Hello

I tried that, and it works with 1:2 and 1:4 resolution.
But in 1:1 resolution I only get 768x540 images ...

Any Idea?
(I am using Debian vdradmin-am 3.6.10-4.1)


Jochen Pawletta

**Comment by MegaV0lt** [comment]
Try to change the values 

```
    my $maxwidth  = 1920;
    my $maxheight = 1080;
```

**Comment by jochenpa** [comment]
Hi

OK, did it.
Now it is limited to 768x576 ...
Could there also be a limit to the vdr process?
I see this in the log:
Dec 11 16:24:55 joshua vdr: [2149200] grabbing to JPEG 70 768 576

Back to the old values (960x540) this is the log entry:
Dec 11 16:27:36 joshua vdr: [2149200] grabbing to JPEG 70 768 540

(vdr version running: 2.4.1-4.1 amd64)

Jochen

**Comment by MegaV0lt** [comment]
I think it depends on the output device and/or source... I make tests tomorrow.

I have vdr 2.6.1 with nvidia card and fullhd resolution...

**Comment by MegaV0lt** [comment]
Please try https://github.com/MegaV0lt/vdradmin-am
Made some change to the template also

**Comment by jochenpa** [comment]
Hi

I tried it directly via telnet to my VDR Port.
It is limited to 768x576 ...
So I don't need to test your new build, but thanks anyway :-)

I have an old Hauppauge Nexus-S card which is not capable of HD (DVB-S2), only SD (DVB-S).

Jochen

**Comment by jochenpa** [comment]
Hi

I now have configured the max values to 768x432, that is the maximum with my card and it works fine ...

Jochen
