### ISSUE TITLE
Consider new version number

### ISSUE THREAD

**Issue by MegaV0lt** [glenvt18/vdradmin-am#3]
I installed this gitversion on my vdr. To avouid confusion about versions it schould at least get a newer version number. 
Eg. 3.6.11
Or at least a flag to indicate the different version Eg. 3.6.10-glenvt18

**Comment by glenvt18** [comment]
I don't know if the original project has been abandoned completely. So, I prefer to keep original version numbers and merge in the future. I've just added the fork suffix - 4ce445e.

**Comment by MegaV0lt** [comment]
OK, that is good for me and anyone else to see that it is a different version...
